### ISSUE TITLE
Add zip() and dictionary comprehension

### ISSUE THREAD

**Issue by aedwardg** [Richard-Burd/python-3-sandbox#2]
@Richard-Burd,

I love this visual cheat sheet!  
Glancing over it, it seems to have just about everything you could want to know about Python.

However, I did notice a couple of things that I use regularly that would fit right in with what you've got:
 - [zip()](https://docs.python.org/3/library/functions.html#zip) and 
- [dictionary comprehensions](https://docs.python.org/3/tutorial/datastructures.html#dictionaries)

That's all I can think of off the top of my head, but if I notice anything else I'll let you know.

Thanks for making these awesome sandbox visualizations!

**Comment by Richard-Burd** [comment]
Thanks @aedwardg for the input, I really appreciate it!

The zip() function and dictionary comprehensions you mentioned above have been added to the latest version of the cheat sheet.
